- name: 'update apt packages'
  become: yes
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: 'upgrade packages'
  become: yes
  apt:
    upgrade: yes

- name: 'install nodejs'
  become: yes
  apt:
    update_cache: yes
    name: ['nodejs', 'npm']
    state: latest

- name: 'install pm2'
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: ansible create directory
  file:
    path: ~/web
    state: directory

- name: Copy file
  template:
    src: 'files/index.js'
    dest: '~/web/index.js'

- name: run the web server
  shell: pm2 start ~/web/index.js -f
